# -*- coding: utf-8 -*-
"""test_mathtravel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QLGvUJCdFStwBS81Chy1RGT-d316XtoD
"""

"""Tests for the mathtravel package"""

from mathtravel import generar_matriz

def test_matriz():
    """A test for the matriz function"""
    assert generar_matriz(ciudades, rango_inicio=10, rango_fin=100) == generar_matriz(ciudades, rango_inicio=10, rango_fin=100)