# -*- coding: utf-8 -*-
"""impresion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dICP-3U2zgdDN6reteX06AJJY2zZ--1h
"""

def imprime(matriz_costo,costo_optimo,ruta_optima):
    return print("La matriz de costos entre ciudades es:")
           print(matriz_costo)
           print("Costo óptimo:", costo_optimo)
           print("Ruta óptima:", ruta_optima)
